#!/bin/sh
#
# Write a version stamp into $1.  $2 is the version string and $3 is
# the compiler name.  Works on Linux; not tested on any other system.
#
# Last edited: Thu Jan  8 17:10:53 1998 by piumarta (Ian Piumarta) on fantasio

if [ -f $1 ]; then
  SERIAL=`head -1 sqUnixVersion.c | cut -d ' ' -f 3 | sed 's/;//'`
  SERIAL=`expr $SERIAL + 1`
else
  SERIAL=1
fi

if expr "$3" : ".*gcc" >/dev/null ; then
  CC=`$3 -v 2>&1 | tail -1 | awk '{print $1 , $3} '`
else
  CC=$3
fi

cat <<_EOF > $1
int vm_serial= $SERIAL;
char *vm_version= "$2";
char *vm_date= "`date`";
char *cc_version= "$CC";
char *ux_version= "`uname -a`";
_EOF
